{{- if and .Values.deployment.enabled (not .Values.statefulset.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reusable-helm-chart.fullname" . }}
  labels:
    {{- include "reusable-helm-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "reusable-helm-chart.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "reusable-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "reusable-helm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "application.initContainers" (list . .Values) | nindent 8 }}
      containers:
        {{- include "application.sidecars" (list . .Values) | nindent 8 }}
        - name: application
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.command }}
          command: {{ . }}
          {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            {{- range .Values.extraConfigMap }}
            {{- if .mountPath }}
            - name: configmap-{{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- range .Values.extraMemoryMount }}
            {{- if .mountPath }}
            - name: memory-{{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- range .Values.extraVolumeMounts }}
            {{- if .mountPath }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- include "reusable-helm-chart.affinity" . | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- range .Values.extraConfigMap }}
        {{- if .mountPath }}
        - name: configmap-{{ .name }}
          configMap:
            name: {{ template "reusable-helm-chart.fullname" $ }}-{{ .name }}
        {{- end }}
        {{- end }}
        {{- range .extraMemoryMount }}
        {{- if .mountPath }}
        - name: memory-{{ .name }}
          emptyDir:
            medium: Memory
            sizeLimit: {{ .sizeLimit }}
        {{- end }}
        {{- end }}
        {{- range .Values.extraVolumeMounts }}
        - name: {{ .name }}
          {{- toYaml .volumeSource | nindent 10 }}
        {{- end }}
{{- end }}
