{{ with .Values.externalSecrets }}
{{- range $key, $value := .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}
spec:
  data:
  {{- range $propertyKey, $propertyValue := $value.properties }}
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $value.path }}
      property: {{ $propertyKey }}
    secretKey: {{ $propertyValue }}
  {{- end }}
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $value.secretStoreName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ $key }}
{{- end }}
{{- end }}

{{- if .Values.dbMigration.enabled }}
{{ with .Values.dbMigration.externalSecrets }}
{{- range $key, $value := .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  data:
  {{- range $propertyKey, $propertyValue := $value.properties }}
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $value.path }}
      property: {{ $propertyKey }}
    secretKey: {{ $propertyValue }}
  {{- end }}
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ $key }}
{{- end }}
{{- end }}
{{- end }}