{{- range .Values.grpcRoutes }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "reusable-helm-chart.fullname" $ }}{{ if .nameSuffix }}-{{ .nameSuffix }}{{ end }}
  labels:
    {{- include "reusable-helm-chart.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- range .parentRefs }}
    - name: {{ .name }}
      namespace: {{ .namespace }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
    {{- end }}
  {{- with .hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .rules }}
    - matches:
        {{- range .matches }}
        - method:
            service: {{ .service }}
            method: {{ .method }}
        {{- end }}
      backendRefs:
        - name: {{ include "reusable-helm-chart.fullname" $ }}
          port: {{ .servicePort }}
    {{- end }}
---
{{- end }}
