{{- range $key, $value := .Values.natsStreams }}
---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: {{ $key }}
  labels:
    {{- include "reusable-helm-chart.labels" $ | nindent 4 }}
spec:
  name: {{ $value.name | default $key }}
  {{- with $value.description }}
  description: {{ . | quote }}
  {{- end }}
  subjects:
    {{- toYaml $value.subjects | nindent 4 }}
  storage: {{ $value.storage | default "file" }}
  {{- with $value.retention }}
  retention: {{ . }}
  {{- end }}
  {{- with $value.replicas }}
  replicas: {{ . }}
  {{- end }}
  {{- with $value.maxAge }}
  maxAge: {{ . }}
  {{- end }}
  {{- with $value.maxBytes }}
  maxBytes: {{ . }}
  {{- end }}
  {{- with $value.maxMsgSize }}
  maxMsgSize: {{ . }}
  {{- end }}
  {{- with $value.maxMsgs }}
  maxMsgs: {{ . }}
  {{- end }}
  {{- with $value.maxConsumers }}
  maxConsumers: {{ . }}
  {{- end }}
  {{- with $value.discard }}
  discard: {{ . }}
  {{- end }}
  {{- with $value.duplicateWindow }}
  duplicateWindow: {{ . }}
  {{- end }}
{{- end }}
