{{- if and .Values.global.rbac.create .Values.global.rbac.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "reusable-helm-chart.rbacName" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "reusable-helm-chart.labels" . | nindent 4 }}
  {{- with .Values.global.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  kind: Role
  name: {{ include "reusable-helm-chart.rbacName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "reusable-helm-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
