{{- range .Values.httpRoutes }}
{{- if .auth }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "reusable-helm-chart.fullname" $ }}{{ if .nameSuffix }}-{{ .nameSuffix }}{{ end }}
  labels:
    {{- include "reusable-helm-chart.labels" $ | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "reusable-helm-chart.fullname" $ }}{{ if .nameSuffix }}-{{ .nameSuffix }}{{ end }}
  {{- with .auth.jwt }}
  jwt:
    providers:
      {{- range .providers }}
      - name: {{ .name }}
        issuer: {{ .issuer }}
        remoteJWKS:
          uri: {{ .jwksUri }}
        {{- with .claimToHeaders }}
        claimToHeaders:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
  {{- end }}
  {{- with .auth.oidc }}
  oidc:
    provider:
      issuer: {{ .issuer }}
    clientID: {{ .clientID }}
    clientSecret:
      name: {{ .clientSecretName }}
    redirectURL: {{ .redirectURL }}
    {{- with .scopes }}
    scopes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
