{{- if and .Values.global.rbac.create .Values.global.rbac.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "reusable-helm-chart.rbacName" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "reusable-helm-chart.labels" . | nindent 4 }}
  {{- with .Values.global.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.global.rbac.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}