{{- range .Values.httpRoutes }}
{{- if or .rateLimit .timeout .requestBuffer .loadBalancer }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "reusable-helm-chart.fullname" $ }}{{ if .nameSuffix }}-{{ .nameSuffix }}{{ end }}-backend-traffic-policy
  labels:
    {{- include "reusable-helm-chart.labels" $ | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "reusable-helm-chart.fullname" $ }}{{ if .nameSuffix }}-{{ .nameSuffix }}{{ end }}
  {{- with .timeout }}
  timeout:
    http:
      requestTimeout: {{ . }}
  {{- end }}
  {{- with .requestBuffer }}
  requestBuffer:
    limit: {{ . }}
  {{- end }}
  {{- with .loadBalancer }}
  loadBalancer:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .rateLimit }}
  rateLimit:
    type: Local
    local:
      rules:
        {{- range .rules }}
        - limit:
            requests: {{ .requests }}
            unit: {{ .unit }}
          {{- with .clientSelectors }}
          clientSelectors:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- range .Values.grpcRoutes }}
{{- if or .timeout .requestBuffer .loadBalancer }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "reusable-helm-chart.fullname" $ }}{{ if .nameSuffix }}-{{ .nameSuffix }}{{ end }}-backend-traffic-policy
  labels:
    {{- include "reusable-helm-chart.labels" $ | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: {{ include "reusable-helm-chart.fullname" $ }}{{ if .nameSuffix }}-{{ .nameSuffix }}{{ end }}
  {{- with .timeout }}
  timeout:
    http:
      requestTimeout: {{ . }}
  {{- end }}
  {{- with .requestBuffer }}
  requestBuffer:
    limit: {{ . }}
  {{- end }}
  {{- with .loadBalancer }}
  loadBalancer:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
