name: Helm Chart Release

on:
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --charts chart

      - name: Run helm lint
        run: helm lint chart

      - name: Run helm template validation
        run: helm template chart --debug

  release:
    needs: lint-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.semantic.outputs.new_release_version }}
      release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote add authenticated-origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Get current version
        id: get_current_version
        run: |
          CURRENT_VERSION=$(grep 'version:' chart/Chart.yaml | sed 's/version: //')
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current Chart.yaml version: $CURRENT_VERSION"

      - name: Semantic versioning
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Chart.yaml version
        if: steps.semantic.outputs.new_release_published == true
        run: |
          NEW_VERSION=${{ steps.semantic.outputs.new_release_version }}
          CURRENT_VERSION=${{ steps.get_current_version.outputs.version }}

          echo "Updating Chart.yaml version from $CURRENT_VERSION to $NEW_VERSION"
          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" chart/Chart.yaml

          git add chart/Chart.yaml
          git commit -m "chore: update chart version to $NEW_VERSION [skip ci]"
          git push authenticated-origin HEAD:release

      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Package Chart
        run: helm package ./chart --destination ./packaged-charts
      - name: Generate Repository Index
        run: |
          helm repo index ./packaged-charts --url https://${{ github.repository_owner }}.github.io/drowzee
        # Popular action to deploy to GitHub Pages:
        # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        if: steps.semantic.outputs.new_release_published == true
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./packaged-charts
          keep_files: true
          force_orphan: true
          destination_dir: .
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
