name: Helm Chart Validation

on:
  push:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "Chart.yaml"
      - "values.yaml"
      - "templates/**"
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "Chart.yaml"
      - "values.yaml"
      - "templates/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --charts chart

      - name: Run helm lint
        run: helm lint chart

      - name: Run helm template validation
        run: helm template chart --debug
