name: Helm Chart Validation and Release

on:
  push:
    branches: [main]
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "Chart.yaml"
      - "values.yaml"
      - "templates/**"
  pull_request:
    branches: [main]
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "Chart.yaml"
      - "values.yaml"
      - "templates/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --charts .

      - name: Run helm lint
        run: helm lint .

      - name: Run helm template validation
        run: helm template . --debug

  release:
    needs: lint-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Semantic versioning
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_PASSWORD }}

      - name: Update Chart.yaml version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          NEW_VERSION=${{ steps.semantic.outputs.new_release_version }}
          CURRENT_VERSION=$(grep 'version:' Chart.yaml | sed 's/version: //')

          echo "Updating Chart.yaml version from $CURRENT_VERSION to $NEW_VERSION"
          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" Chart.yaml

          git add Chart.yaml
          git commit -m "chore: update chart version to $NEW_VERSION [skip ci]"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package . --destination .cr-release-packages

      - name: Upload Helm chart as artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: .cr-release-packages/*.tgz

      - name: Set up chart-releaser
        uses: helm/chart-releaser-action@v1
        with:
          charts_dir: .
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
